[package]
name = "linux-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
appstream = "0.2.2"
slint = "1.15.0"

[build-dependencies]
slint-build = "1.15.0"
